language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libevent-dev libevent-openssl-2.0 -qq
  - sudo apt-get install libpq-dev -qq
script: make dev
