language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libevent-dev libevent-openssl-2.0
  - sudo apt-get install -qq libpq-dev
script: make dev
